export interface CityData {
    city: string;
    state: string;
    region: string;
}

export const INDIAN_CITIES: CityData[] = [
    // A
    { city: "Agra", state: "Uttar Pradesh", region: "North India" },
    { city: "Ahmedabad", state: "Gujarat", region: "Western India" },
    { city: "Aizawl", state: "Mizoram", region: "North East India" },
    { city: "Ajmer", state: "Rajasthan", region: "Western India" },
    { city: "Aligarh", state: "Uttar Pradesh", region: "North India" },
    { city: "Allahabad", state: "Uttar Pradesh", region: "North India" },
    { city: "Alwar", state: "Rajasthan", region: "Western India" },
    { city: "Ambala", state: "Haryana", region: "North India" },
    { city: "Amla", state: "Madhya Pradesh", region: "Central India" },
    { city: "Amravati", state: "Maharashtra", region: "Western India" },
    { city: "Amritsar", state: "Punjab", region: "North India" },
    { city: "Anand", state: "Gujarat", region: "Western India" },
    { city: "Anantapur", state: "Andhra Pradesh", region: "South India" },
    { city: "Aurangabad", state: "Maharashtra", region: "Western India" },
    // B
    { city: "Bambora", state: "Rajasthan", region: "Western India" },
    { city: "Bandhavgarh", state: "Madhya Pradesh", region: "Central India" },
    { city: "Bangalore", state: "Karnataka", region: "South India" },
    { city: "Bareilly", state: "Uttar Pradesh", region: "North India" },
    { city: "Bathinda", state: "Punjab", region: "North India" },
    { city: "Belgaum", state: "Karnataka", region: "South India" },
    { city: "Bellary", state: "Karnataka", region: "South India" },
    { city: "Bharatpur", state: "Rajasthan", region: "Western India" },
    { city: "Bhilai", state: "Chhattisgarh", region: "Central India" },
    { city: "Bhiwani", state: "Haryana", region: "North India" },
    { city: "Bhopal", state: "Madhya Pradesh", region: "Central India" },
    { city: "Bhubaneswar", state: "Odisha", region: "Eastern India" },
    { city: "Bikaner", state: "Rajasthan", region: "Western India" },
    { city: "Bilaspur", state: "Chhattisgarh", region: "Central India" },
    { city: "Bokaro", state: "Jharkhand", region: "Eastern India" },
    // C
    { city: "Calicut", state: "Kerala", region: "South India" },
    { city: "Chail", state: "Himachal Pradesh", region: "North India" },
    { city: "Chamba", state: "Himachal Pradesh", region: "North India" },
    { city: "Chandigarh", state: "Chandigarh", region: "North India" },
    { city: "Chennai", state: "Tamil Nadu", region: "South India" },
    { city: "Chittorgarh", state: "Rajasthan", region: "Western India" },
    { city: "Coimbatore", state: "Tamil Nadu", region: "South India" },
    { city: "Cuttack", state: "Odisha", region: "Eastern India" },
    // D
    { city: "Dalhousie", state: "Himachal Pradesh", region: "North India" },
    { city: "Darbhanga", state: "Bihar", region: "Eastern India" },
    { city: "Darjeeling", state: "West Bengal", region: "Eastern India" },
    { city: "Dausa", state: "Rajasthan", region: "Western India" },
    { city: "Dehradun", state: "Uttarakhand", region: "North India" },
    { city: "Dhanbad", state: "Jharkhand", region: "Eastern India" },
    { city: "Dharamshala", state: "Himachal Pradesh", region: "North India" },
    { city: "Dibrugarh", state: "Assam", region: "North East India" },
    { city: "Durgapur", state: "West Bengal", region: "Eastern India" },
    // E
    { city: "Erode", state: "Tamil Nadu", region: "South India" },
    // F
    { city: "Faridabad", state: "Haryana", region: "North India" },
    { city: "Fatehpur", state: "Uttar Pradesh", region: "North India" },
    // G
    { city: "Gangtok", state: "Sikkim", region: "Eastern India" },
    { city: "Gaya", state: "Bihar", region: "Eastern India" },
    { city: "Ghaziabad", state: "Uttar Pradesh", region: "North India" },
    { city: "Goa", state: "Goa", region: "Western India" },
    { city: "Gorakhpur", state: "Uttar Pradesh", region: "North India" },
    { city: "Guntur", state: "Andhra Pradesh", region: "South India" },
    { city: "Gurgaon", state: "Haryana", region: "North India" },
    { city: "Guwahati", state: "Assam", region: "North East India" },
    { city: "Gwalior", state: "Madhya Pradesh", region: "Central India" },
    // H
    { city: "Hanamkonda", state: "Telangana", region: "South India" },
    { city: "Hansi", state: "Haryana", region: "North India" },
    { city: "Haridwar", state: "Uttarakhand", region: "North India" },
    { city: "Hisar", state: "Haryana", region: "North India" },
    { city: "Hosur", state: "Tamil Nadu", region: "South India" },
    { city: "Howrah", state: "West Bengal", region: "Eastern India" },
    { city: "Hubli", state: "Karnataka", region: "South India" },
    { city: "Hyderabad", state: "Telangana", region: "South India" },
    // I
    { city: "Imphal", state: "Manipur", region: "North East India" },
    { city: "Indore", state: "Madhya Pradesh", region: "Central India" },
    { city: "Itanagar", state: "Arunachal Pradesh", region: "North East India" },
    // J
    { city: "Jabalpur", state: "Madhya Pradesh", region: "Central India" },
    { city: "Jaipur", state: "Rajasthan", region: "Western India" },
    { city: "Jaisalmer", state: "Rajasthan", region: "Western India" },
    { city: "Jalandhar", state: "Punjab", region: "North India" },
    { city: "Jalgaon", state: "Maharashtra", region: "Western India" },
    { city: "Jammu", state: "Jammu & Kashmir", region: "North India" },
    { city: "Jamshedpur", state: "Jharkhand", region: "Eastern India" },
    { city: "Jhansi", state: "Uttar Pradesh", region: "North India" },
    { city: "Jodhpur", state: "Rajasthan", region: "Western India" },
    { city: "Junagadh", state: "Gujarat", region: "Western India" },
    // K
    { city: "Kakinada", state: "Andhra Pradesh", region: "South India" },
    { city: "Kancheepuram", state: "Tamil Nadu", region: "South India" },
    { city: "Kanha", state: "Madhya Pradesh", region: "Central India" },
    { city: "Kanpur", state: "Uttar Pradesh", region: "North India" },
    { city: "Karnal", state: "Haryana", region: "North India" },
    { city: "Khimsar", state: "Rajasthan", region: "Western India" },
    { city: "Kochi", state: "Kerala", region: "South India" },
    { city: "Kohima", state: "Nagaland", region: "North East India" },
    { city: "Kolhapur", state: "Maharashtra", region: "Western India" },
    { city: "Kolkata", state: "West Bengal", region: "Eastern India" },
    { city: "Kota", state: "Rajasthan", region: "Western India" },
    { city: "Kottayam", state: "Kerala", region: "South India" },
    { city: "Kozhikode", state: "Kerala", region: "South India" },
    // L
    { city: "Leh", state: "Ladakh", region: "North India" },
    { city: "Lucknow", state: "Uttar Pradesh", region: "North India" },
    { city: "Ludhiana", state: "Punjab", region: "North India" },
    // M
    { city: "Madurai", state: "Tamil Nadu", region: "South India" },
    { city: "Mahabaleshwar", state: "Maharashtra", region: "Western India" },
    { city: "Manali", state: "Himachal Pradesh", region: "North India" },
    { city: "Mandavi", state: "Gujarat", region: "Western India" },
    { city: "Mangalore", state: "Karnataka", region: "South India" },
    { city: "Marchula", state: "Uttarakhand", region: "North India" },
    { city: "Mathura", state: "Uttar Pradesh", region: "North India" },
    { city: "Meerut", state: "Uttar Pradesh", region: "North India" },
    { city: "Moradabad", state: "Uttar Pradesh", region: "North India" },
    { city: "Mount Abu", state: "Rajasthan", region: "Western India" },
    { city: "Mumbai", state: "Maharashtra", region: "Western India" },
    { city: "Mussoorie", state: "Uttarakhand", region: "North India" },
    { city: "Muzaffarpur", state: "Bihar", region: "Eastern India" },
    { city: "Mysore", state: "Karnataka", region: "South India" },
    // N
    { city: "Nagaur", state: "Rajasthan", region: "Western India" },
    { city: "Nagpur", state: "Maharashtra", region: "Western India" },
    { city: "Nainital", state: "Uttarakhand", region: "North India" },
    { city: "Nanded", state: "Maharashtra", region: "Western India" },
    { city: "Nashik", state: "Maharashtra", region: "Western India" },
    { city: "Navi Mumbai", state: "Maharashtra", region: "Western India" },
    { city: "New Delhi", state: "Delhi", region: "North India" },
    { city: "Noida", state: "Uttar Pradesh", region: "North India" },
    // O
    { city: "Ooty", state: "Tamil Nadu", region: "South India" },
    // P
    { city: "Palampur", state: "Himachal Pradesh", region: "North India" },
    { city: "Pali", state: "Rajasthan", region: "Western India" },
    { city: "Panaji", state: "Goa", region: "Western India" },
    { city: "Panchkula", state: "Haryana", region: "North India" },
    { city: "Panipat", state: "Haryana", region: "North India" },
    { city: "Patna", state: "Bihar", region: "Eastern India" },
    { city: "Pench", state: "Maharashtra", region: "Western India" },
    { city: "Phalodi", state: "Rajasthan", region: "Western India" },
    { city: "Pondicherry", state: "Puducherry", region: "South India" },
    { city: "Port Blair", state: "Andaman & Nicobar Islands", region: "South India" },
    { city: "Pragpur", state: "Himachal Pradesh", region: "North India" },
    { city: "Prayagraj", state: "Uttar Pradesh", region: "North India" },
    { city: "Pune", state: "Maharashtra", region: "Western India" },
    { city: "Pushkar", state: "Rajasthan", region: "Western India" },
    // R
    { city: "Raipur", state: "Chhattisgarh", region: "Central India" },
    { city: "Rajahmundry", state: "Andhra Pradesh", region: "South India" },
    { city: "Rajkot", state: "Gujarat", region: "Western India" },
    { city: "Ram Nagar", state: "Uttar Pradesh", region: "North India" },
    { city: "Ramgarh", state: "Rajasthan", region: "Western India" },
    { city: "Ranakpur", state: "Rajasthan", region: "Western India" },
    { city: "Ranchi", state: "Jharkhand", region: "Eastern India" },
    { city: "Ranthambore", state: "Rajasthan", region: "Western India" },
    { city: "Rishikesh", state: "Uttarakhand", region: "North India" },
    { city: "Rohtak", state: "Haryana", region: "North India" },
    { city: "Rohetgarh", state: "Rajasthan", region: "Western India" },
    { city: "Rourkela", state: "Odisha", region: "Eastern India" },
    // S
    { city: "Saharanpur", state: "Uttar Pradesh", region: "North India" },
    { city: "Salem", state: "Tamil Nadu", region: "South India" },
    { city: "Sangli", state: "Maharashtra", region: "Western India" },
    { city: "Sasan Gir", state: "Gujarat", region: "Western India" },
    { city: "Sawai Madhopur", state: "Rajasthan", region: "Western India" },
    { city: "Shimla", state: "Himachal Pradesh", region: "North India" },
    { city: "Shirdi", state: "Maharashtra", region: "Western India" },
    { city: "Shuklaganj", state: "Uttar Pradesh", region: "North India" },
    { city: "Siliguri", state: "West Bengal", region: "Eastern India" },
    { city: "Solapur", state: "Maharashtra", region: "Western India" },
    { city: "Sonipat", state: "Haryana", region: "North India" },
    { city: "Srinagar", state: "Jammu & Kashmir", region: "North India" },
    { city: "Surat", state: "Gujarat", region: "Western India" },
    // T
    { city: "Thane", state: "Maharashtra", region: "Western India" },
    { city: "Thekkady", state: "Kerala", region: "South India" },
    { city: "Thiruvananthapuram", state: "Kerala", region: "South India" },
    { city: "Thrissur", state: "Kerala", region: "South India" },
    { city: "Tirupati", state: "Andhra Pradesh", region: "South India" },
    { city: "Tirupur", state: "Tamil Nadu", region: "South India" },
    { city: "Trichy", state: "Tamil Nadu", region: "South India" },
    { city: "Trivandrum", state: "Kerala", region: "South India" },
    // U
    { city: "Udaipur", state: "Rajasthan", region: "Western India" },
    { city: "Ujjain", state: "Madhya Pradesh", region: "Central India" },
    { city: "Unnao", state: "Uttar Pradesh", region: "North India" },
    // V
    { city: "Vadodara", state: "Gujarat", region: "Western India" },
    { city: "Vapi", state: "Gujarat", region: "Western India" },
    { city: "Varanasi", state: "Uttar Pradesh", region: "North India" },
    { city: "Vellore", state: "Tamil Nadu", region: "South India" },
    { city: "Vijayawada", state: "Andhra Pradesh", region: "South India" },
    { city: "Visakhapatnam", state: "Andhra Pradesh", region: "South India" },
    // W
    { city: "Warangal", state: "Telangana", region: "South India" },
    // Y
    { city: "Yamunanagar", state: "Haryana", region: "North India" },
];

// Get unique states
export const INDIAN_STATES = [...new Set(INDIAN_CITIES.map(c => c.state))].sort();
